version: "3.8"
services:
  springboot-restful-webservices:
    container_name: springboot-restful-webservices
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - mysqldb
    environment:
      - spring.jpa.hibernate.ddl-auto=update
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/bancodb
      - spring.datasource.username=usuario
      - spring.datasource.password=contraseña
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

  mysqldb:
    container_name: mysqldb
    image: mysql
    ports:
      - 8090:3306
    environment:
      MYSQL_USER: usuario
      MYSQL_PASSWORD: contraseña
      MYSQL_DATABASE: bancodb
      MYSQL_ROOT_PASSWORD: root
