name: Continuous Integration

on:
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 'adopt@1.20'

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v1
        with:
          gradle-version: '7.0'
          tasks: 'build'

      - name: Run Unit Tests
        run: gradle test
